### ISSUE TITLE
Seo fields repeated in backend repeater field

### ISSUE THREAD

**Issue by faselunare** [suresoftware/october-power-seo#5]
When I'm using Rainlab.StaticPages and a repeater field

{repeater name="services" prompt="Add new benefit" tab="Services"}
    {variable type="text" name="headline" label="Headline"}{/variable}
    {variable type="staticpagepicker" name="page" label="Service Page" emptyOption="- No Page -"}{/variable}
    {variable type="richeditor" name="description" label="Description"}{/variable}
{/repeater}
in the backend the SEO fields are being added to a repeater form. It's not supposed to happen I guess

**Comment by Humni** [comment]
Am working on re-creating this issue now

**Comment by sqwk** [comment]
Is there any way to hide the SEO field from the repeater?

I also attached a screenshot that shows the duplicated fields.
<img width="849" alt="Screen Shot" src="https://user-images.githubusercontent.com/1353312/57024688-801d9680-6c35-11e9-8074-c90c47faacf8.png">

**Comment by Humni** [comment]
I think there are use cases for this, I have been able to replicate this. Any suggestions on how best to hide it in specific situations?

**Comment by SplicedWeb** [comment]
I've had a similar issue with "Custom Fields" plugin.
The support from that plugin creator is shown here to fix a suggested "bug"
https://octobercms.com/plugin/support/shohabbos-customfields/question-related-to-use-with-power-seo-plugin?page=1

**Comment by Humni** [comment]
This has been resolved in the latest release 2.0.4

**Comment by sqwk** [comment]
After the update, I still have the fields visible for each repeater. Is there anything else that I need to do to hide them?

Code is as follows:

    {repeater name="sections" tab="Sections" prompt="Add a section"}
        {variable name="title" type="text" span="left"}{/variable}
        {variable name="content" type="richeditor"}{/variable}
    {/repeater}
